### ISSUE TITLE
Support of radio buttons and select menus

### ISSUE THREAD

**Issue by harry-boldt** [aschempp/contao-conditionalforms#1]
The check box works fine for separate information. It would be a huge improvement, if one could provide additional fields depending on a value of a given radio or selection group or what kind of field ever. Just like

Show this field, if &lt;fieldname&gt; = &lt;fieldvalue&gt;. 
Even better: An option to append more citeria like: AND/OR &lt;fieldname2&gt; = &lt;fieldvalue2&gt;.

Regards
Harry

**Comment by aschempp** [comment]
use https://github.com/terminal42/contao-conditionalformfields
