### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by Luminanz** [aschempp/contao-conditionalforms#3]
Soweit ich es verstanden habe läuft diese Erweiterung nur mit mootools. Es wäre schön, wenn es auch mit jquery (und ohne mootools) funktionieren würde.
Allenfalls würde es ausreichen, ein template zur Verfügung zustellen, worin die Änderung updatesicher vorgenommen werden kann.
Besten Dank

**Comment by klauswagner** [comment]
+1

siehe auch:
https://community.contao.org/de/showthread.php?35919-conditionalforms-mit-jQuery

**Comment by aschempp** [comment]
see https://github.com/terminal42/contao-conditionalformfields
